// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApAOq_Gni23ihquvNqVgkJYSISHjVim8o',
    appId: '1:153613114666:web:9ebc0f3fe1c2fd583ed253',
    messagingSenderId: '153613114666',
    projectId: 'ecommerceapp-db0a3',
    authDomain: 'ecommerceapp-db0a3.firebaseapp.com',
    storageBucket: 'ecommerceapp-db0a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5Fqe6huq4Z4aXvLhRLwZ1ifP3kBdgZ8',
    appId: '1:153613114666:android:ffbf6b66e63dba143ed253',
    messagingSenderId: '153613114666',
    projectId: 'ecommerceapp-db0a3',
    storageBucket: 'ecommerceapp-db0a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvlJND0pbprhmd58L_nB4FVzIQHgLn6hw',
    appId: '1:153613114666:ios:a834125ca8d9cb2e3ed253',
    messagingSenderId: '153613114666',
    projectId: 'ecommerceapp-db0a3',
    storageBucket: 'ecommerceapp-db0a3.firebasestorage.app',
    androidClientId: '153613114666-u9mpfgbv8suu1ejcrgb0c16hrb3d44dd.apps.googleusercontent.com',
    iosClientId: '153613114666-qqk3nceeg39cg6u1d2dmfrp70g4ll4b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ss30Ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvlJND0pbprhmd58L_nB4FVzIQHgLn6hw',
    appId: '1:153613114666:ios:a834125ca8d9cb2e3ed253',
    messagingSenderId: '153613114666',
    projectId: 'ecommerceapp-db0a3',
    storageBucket: 'ecommerceapp-db0a3.firebasestorage.app',
    androidClientId: '153613114666-u9mpfgbv8suu1ejcrgb0c16hrb3d44dd.apps.googleusercontent.com',
    iosClientId: '153613114666-qqk3nceeg39cg6u1d2dmfrp70g4ll4b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ss30Ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApAOq_Gni23ihquvNqVgkJYSISHjVim8o',
    appId: '1:153613114666:web:b3961229cdb8dd2c3ed253',
    messagingSenderId: '153613114666',
    projectId: 'ecommerceapp-db0a3',
    authDomain: 'ecommerceapp-db0a3.firebaseapp.com',
    storageBucket: 'ecommerceapp-db0a3.firebasestorage.app',
  );

}